# Guest OS timezone
timezone: Europe/Budapest

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: ticketing-system-template.test

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024

network: 'private_network'

# Virtual machine IP
ip: 192.168.83.123

domains:
  frontend: ticketing-system-template.test
